package com.theevilroot.ampaster

import com.google.gson.GsonBuilder
import com.google.gson.JsonParser

object TheHolder {

    val jsonParser = JsonParser()
    val gsonBuilder = GsonBuilder().setPrettyPrinting().create()

    // TODO("MUST BE REMOVED BEFORE GIT PUSH")
    val PASTEBIN_DEV_TOKEN = ""
    var user: User? = null

    val highlightings = mapOf(
            "null" to "No Syntax Highlight",
            "4cs" to "4CS",
            "6502acme" to "6502 ACME Cross Assembler",
            "6502kickass" to "6502 Kick Assembler",
            "6502tasm" to "6502 TASM/64TASS",
            "abap" to "ABAP",
            "actionscript" to "ActionScript",
            "actionscript3" to "ActionScript 3",
            "ada" to "Ada",
            "aimms" to "AIMMS",
            "algol68" to "ALGOL 68",
            "apache" to "Apache Log",
            "applescript" to "AppleScript",
            "apt_sources" to "APT Sources",
            "arm" to "ARM",
            "asm" to "ASM (NASM)",
            "asp" to "ASP",
            "asymptote" to "Asymptote",
            "autoconf" to "autoconf",
            "autohotkey" to "Autohotkey",
            "autoit" to "AutoIt",
            "avisynth" to "Avisynth",
            "awk" to "Awk",
            "bascomavr" to "BASCOM AVR",
            "bash" to "Bash",
            "basic4gl" to "Basic4GL",
            "dos" to "Batch",
            "bibtex" to "BibTeX",
            "blitzbasic" to "Blitz Basic",
            "b3d" to "Blitz3D",
            "bmx" to "BlitzMax",
            "bnf" to "BNF",
            "boo" to "BOO",
            "bf" to "BrainFuck",
            "c" to "C",
            "c_winapi" to "C (WinAPI)",
            "c_mac" to "C for Macs",
            "cil" to "C Intermediate Language",
            "csharp" to "C#",
            "cpp" to "C++",
            "cpp-winapi" to "C++ (WinAPI)",
            "cpp-qt" to "C++ (with Qt extension)",
            "c_loadrunner" to "C: Loadrunner",
            "caddcl" to "CAD DCL",
            "cadlisp" to "CAD Lisp",
            "ceylon" to "Ceylon",
            "cfdg" to "CFDG",
            "chaiscript" to "ChaiScript",
            "chapel" to "Chapel",
            "clojure" to "Clojure",
            "klonec" to "Clone C",
            "klonecpp" to "Clone C++",
            "cmake" to "CMake",
            "cobol" to "COBOL",
            "coffeescript" to "CoffeeScript",
            "cfm" to "ColdFusion",
            "css" to "CSS",
            "cuesheet" to "Cuesheet",
            "d" to "D",
            "dart" to "Dart",
            "dcl" to "DCL",
            "dcpu16" to "DCPU-16",
            "dcs" to "DCS",
            "delphi" to "Delphi",
            "oxygene" to "Delphi Prism (Oxygene)",
            "diff" to "Diff",
            "div" to "DIV",
            "dot" to "DOT",
            "e" to "E",
            "ezt" to "Easytrieve",
            "ecmascript" to "ECMAScript",
            "eiffel" to "Eiffel",
            "email" to "Email",
            "epc" to "EPC",
            "erlang" to "Erlang",
            "euphoria" to "Euphoria",
            "fsharp" to "F#",
            "falcon" to "Falcon",
            "filemaker" to "Filemaker",
            "fo" to "FO Language",
            "f1" to "Formula One",
            "fortran" to "Fortran",
            "freebasic" to "FreeBasic",
            "freeswitch" to "FreeSWITCH",
            "gambas" to "GAMBAS",
            "gml" to "Game Maker",
            "gdb" to "GDB",
            "genero" to "Genero",
            "genie" to "Genie",
            "gettext" to "GetText",
            "go" to "Go",
            "groovy" to "Groovy",
            "gwbasic" to "GwBasic",
            "haskell" to "Haskell",
            "haxe" to "Haxe",
            "hicest" to "HicEst",
            "hq9plus" to "HQ9 Plus",
            "html4strict" to "HTML",
            "html5" to "HTML 5",
            "icon" to "Icon",
            "idl" to "IDL",
            "ini" to "INI file",
            "inno" to "Inno Script",
            "intercal" to "INTERCAL",
            "io" to "IO",
            "ispfpanel" to "ISPF Panel Definition",
            "j" to "J",
            "java" to "Java",
            "java5" to "Java 5",
            "javascript" to "JavaScript",
            "jcl" to "JCL",
            "jquery" to "jQuery",
            "json" to "JSON",
            "julia" to "Julia",
            "kixtart" to "KiXtart",
            "kotlin" to "Kotlin",
            "latex" to "Latex",
            "ldif" to "LDIF",
            "lb" to "Liberty BASIC",
            "lsl2" to "Linden Scripting",
            "lisp" to "Lisp",
            "llvm" to "LLVM",
            "locobasic" to "Loco Basic",
            "logtalk" to "Logtalk",
            "lolcode" to "LOL Code",
            "lotusformulas" to "Lotus Formulas",
            "lotusscript" to "Lotus Script",
            "lscript" to "LScript",
            "lua" to "Lua",
            "m68k" to "M68000 Assembler",
            "magiksf" to "MagikSF",
            "make" to "Make",
            "mapbasic" to "MapBasic",
            "markdown" to "Markdown",
            "matlab" to "MatLab",
            "mirc" to "mIRC",
            "mmix" to "MIX Assembler",
            "modula2" to "Modula 2",
            "modula3" to "Modula 3",
            "68000devpac" to "Motorola 68000 HiSoft Dev",
            "mpasm" to "MPASM",
            "mxml" to "MXML",
            "mysql" to "MySQL",
            "nagios" to "Nagios",
            "netrexx" to "NetRexx",
            "newlisp" to "newLISP",
            "nginx" to "Nginx",
            "nim" to "Nim",
            "text" to "None",
            "nsis" to "NullSoft Installer",
            "oberon2" to "Oberon 2",
            "objeck" to "Objeck Programming Language",
            "objc" to "Objective C",
            "ocaml-brief" to "OCalm Brief",
            "ocaml" to "OCaml",
            "octave" to "Octave",
            "oorexx" to "Open Object Rexx",
            "pf" to "OpenBSD PACKET FILTER",
            "glsl" to "OpenGL Shading",
            "oobas" to "Openoffice BASIC",
            "oracle11" to "Oracle 11",
            "oracle8" to "Oracle 8",
            "oz" to "Oz",
            "parasail" to "ParaSail",
            "parigp" to "PARI/GP",
            "pascal" to "Pascal",
            "pawn" to "Pawn",
            "pcre" to "PCRE",
            "per" to "Per",
            "perl" to "Perl",
            "perl6" to "Perl 6",
            "php" to "PHP",
            "php-brief" to "PHP Brief",
            "pic16" to "Pic 16",
            "pike" to "Pike",
            "pixelbender" to "Pixel Bender",
            "pli" to "PL/I",
            "plsql" to "PL/SQL",
            "postgresql" to "PostgreSQL",
            "postscript" to "PostScript",
            "povray" to "POV-Ray",
            "powerbuilder" to "PowerBuilder",
            "powershell" to "PowerShell",
            "proftpd" to "ProFTPd",
            "progress" to "Progress",
            "prolog" to "Prolog",
            "properties" to "Properties",
            "providex" to "ProvideX",
            "puppet" to "Puppet",
            "purebasic" to "PureBasic",
            "pycon" to "PyCon",
            "python" to "Python",
            "pys60" to "Python for S60",
            "q" to "q/kdb+",
            "qbasic" to "QBasic",
            "qml" to "QML",
            "rsplus" to "R",
            "racket" to "Racket",
            "rails" to "Rails",
            "rbs" to "RBScript",
            "rebol" to "REBOL",
            "reg" to "REG",
            "rexx" to "Rexx",
            "robots" to "Robots",
            "rpmspec" to "RPM Spec",
            "ruby" to "Ruby",
            "gnuplot" to "Ruby Gnuplot",
            "rust" to "Rust",
            "sas" to "SAS",
            "scala" to "Scala",
            "scheme" to "Scheme",
            "scilab" to "Scilab",
            "scl" to "SCL",
            "sdlbasic" to "SdlBasic",
            "smalltalk" to "Smalltalk",
            "smarty" to "Smarty",
            "spark" to "SPARK",
            "sparql" to "SPARQL",
            "sqf" to "SQF",
            "sql" to "SQL",
            "standardml" to "StandardML",
            "stonescript" to "StoneScript",
            "sclang" to "SuperCollider",
            "swift" to "Swift",
            "systemverilog" to "SystemVerilog",
            "tsql" to "T-SQL",
            "tcl" to "TCL",
            "teraterm" to "Tera Term",
            "thinbasic" to "thinBasic",
            "typoscript" to "TypoScript",
            "unicon" to "Unicon",
            "uscript" to "UnrealScript",
            "upc" to "UPC",
            "urbi" to "Urbi",
            "vala" to "Vala",
            "vbnet" to "VB.NET",
            "vbscript" to "VBScript",
            "vedit" to "Vedit",
            "verilog" to "VeriLog",
            "vhdl" to "VHDL",
            "vim" to "VIM",
            "visualprolog" to "Visual Pro Log",
            "vb" to "VisualBasic",
            "visualfoxpro" to "VisualFoxPro",
            "whitespace" to "WhiteSpace",
            "whois" to "WHOIS",
            "winbatch" to "Winbatch",
            "xbasic" to "XBasic",
            "xml" to "XML",
            "xorg_conf" to "Xorg Config",
            "xpp" to "XPP",
            "yaml" to "YAML",
            "z80" to "Z80 Assembler",
            "zxbasic" to "ZXBasic"
    )

    val expirations = mapOf(
            "Никогда" to "N",
            "10 Минут" to "1M",
            "Час" to "1H",
            "День" to "1D",
            "Неделя" to "1W",
            "Две Недели" to "2W",
            "Месяц" to "1M",
            "Полгода" to "6M",
            "Год" to "1Y"
    )

    val visibilities = mapOf(
            "Публичный" to "0",
            "Не отображаемый" to "1",
            "Приватный(Pro)" to "2"
    )

}